# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    ignore:
      - dependency-name: "some-package"
        versions: ["1.0.0", "2.0.0"]
    target-branch: "v0.0.0"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
    commit-message:
      prefix: "fix"
      prefix-development: "fix"
    ignore:
      - dependency-name: "some-package"
        versions: ["1.0.0", "2.0.0"]
    target-branch: "v0.0.0"

security-updates:
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  labels:
    - "security"
  commit-message:
    prefix: "fix"
    prefix-development: "fix"
  target-branch: "v0.0.0"
